"""add fingerprint to tire_specifications

Revision ID: 29962aedcfe3
Revises: 1e5534b53998
Create Date: 2026-06-12 11:54:05.552888
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '29962aedcfe3'
down_revision: Union[str, None] = '1e5534b53998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tire_specifications', sa.Column('fingerprint', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'tire_specifications', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tire_specifications', type_='unique')
    op.drop_column('tire_specifications', 'fingerprint')
    # ### end Alembic commands ###
